# Generated by Django 6.0.6 on 2026-06-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.store'),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='sub_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='orders.suborder'),
        ),
    ]
